baseURL = "https://yoooo.fun/"
title = "Aurora"
languageCode = "en-us"
footnoteReturnLinkContents = "↩"
#theme = ["github.com/reuixiy/hugo-theme-meme"]
#theme = ["github.com/CaiJimmy/hugo-theme-stack"]
theme = ["github.com/miiiku/hugo-theme-kagome"]

[params]
AuthorName = "Mystic"
GitHubUser = "pplmx"
SidebarRecentLimit = 5
Subtitle = "To infinity and beyond."
