# 顶部导航栏
[[main]]
identifier = "/"
name = "🏠 HOME"
title = "HOME"
url = "/"
weight = 1

[[main]]
identifier = "/posts"
name = "🗂️ POSTS"
title = "POSTS"
url = "/posts"
weight = 2

[[main]]
identifier = "/about"
name = "😈 ABOUT"
title = "ABOUT"
url = "/46b3931b9959c927df4fc65fdee94b07"
weight = 3

[[main]]
identifier = "/link"
name = "🔗 LINK"
title = "LINK"
url = "/807765384d9d5527da8848df14a4f02f"
weight = 4

# 底部社交图标
[[social]]
identifier = "github"
name = "github"
url = "https://github.com/pplmx"
weight = 1
