keywords = ["yoooo.fun", "caoyu.info", "hugo", "blog", "个人博客", "主题"]
description = "To infinity and beyond"
mainSections = ["posts"]
toc_show_len = 300

[analytics]
baidu = ""

[widget]
articles_count = 6
categories_count = 6
tags_count = 12

[aplayer]
theme = "#b7daff"
autoplay = false
loop = "none"
mutex = true

[dplayer]
theme = "#b7daff"
autoplay = false
loop = false
mutex = true
