baseURL = "https://yoooo.fun/"
title = "Aurora"
languageCode = "en-us"
footnoteReturnLinkContents = "↩"
#theme = ["github.com/wangchucheng/hugo-eureka"]
#theme = ["github.com/razonyang/hugo-theme-bootstrap"]
theme = ["github.com/reuixiy/hugo-theme-meme"]

[params]
AuthorName = "Mystic"
GitHubUser = "pplmx"
SidebarRecentLimit = 5
Subtitle = "To infinity and beyond."
