baseURL = "https://yoooo.fun/"
title = "Aurora"
languageCode = "en-us"
footnoteReturnLinkContents = "↩"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
AuthorName = "Mystic"
GitHubUser = "pplmx"
SidebarRecentLimit = 5
Subtitle = "To infinity and beyond."
