name: github pages

on:
    workflow_dispatch:
    push:
        branches:
            - main  # Set a branch to deploy

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
                with:
                    submodules: recursive  # Fetch the Docsy theme
                    fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

            -   name: Setup Hugo
                uses: peaceiris/actions-hugo@v2
                with:
                    hugo-version: 'latest'
                    extended: true

            -   run: hugo --minify -F

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    force_orphan: true
                    commit_message: ${{ github.event.head_commit.message }}
