name: github pages

on:
    workflow_dispatch:
    push:
        branches:
            - main  # Set a branch to deploy

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout yoooo.fun repo
                uses: actions/checkout@v4
                with:
                    submodules: recursive  # Fetch the Docsy theme
                    fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
                    path: hugo             # like as "git clone <repo_url> hugo"
            -   name: Checkout caoyu.info repo
                uses: actions/checkout@v4
                with:
                    repository: pplmx/caoyu.info
                    token: ${{ secrets.PAT }}
                    path: hexo             # like as "git clone <repo_url> hexo"

            -   name: Setup Go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.21'

            -   name: Install h2h
                run: go install github.com/pplmx/h2h@latest

            -   name: Convert hexo posts to hugo posts
                run: |
                    # remove the old
                    rm -fr hugo/static/{assets,images}
                    rm -fr hugo/content/posts
                    # copy the new
                    cp -r hexo/source/assets hugo/static/assets
                    cp -r hexo/source/images hugo/static/images
                    # convert the posts
                    h2h --src hexo/source/_posts --dst hugo/content/posts --format yaml --direction hexo2hugo

            -   name: Commit & Push
                run: |
                    cd hugo
                    git config --local user.email "215104920@qq.com"
                    git config --local user.name "Hexo2Hugo[bot]"
                    git add .
                    git commit -m "Convert hexo posts to hugo posts"
                    git push

            -   name: Setup Hugo
                uses: peaceiris/actions-hugo@v2
                with:
                    hugo-version: 'latest'
                    extended: true

            -   run: hugo --minify

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    force_orphan: true
                    commit_message: ${{ github.event.head_commit.message }}
